---
- name: Install nginx.
  apt:
    name: nginx
    state: present

- name: Remove nginx default virtualhost.
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Upload nginx configuration file.
  template:
    src: nginx-aptly.conf.j2
    dest: /etc/nginx/sites-available/aptly.conf
    owner: root
    group: root
    mode: "644"
  notify: restart nginx

- name: Create nginx configuration symlinks.
  file:
    src: /etc/nginx/sites-available/aptly.conf
    dest: /etc/nginx/sites-enabled/aptly.conf
    state: link
  notify: restart nginx
